name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hello! Thank you for your feedback, I will review it as soon as possible. 🚀"
        pr-message: "Thank you for your contribution! I will review your PR and get back to you. 🎉"
